---
development:
  cloud_name: photo-plop
  api_key: '879612774687551'
  api_secret: GVg1lXuOPsFsXVpTZHp-PY79tBg
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: photo-plop
  api_key: '879612774687551'
  api_secret: GVg1lXuOPsFsXVpTZHp-PY79tBg
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: photo-plop
  api_key: '879612774687551'
  api_secret: GVg1lXuOPsFsXVpTZHp-PY79tBg
  enhance_image_tag: true
  static_image_support: false
